version: '2'
#
services:
  iris:
    image: containers.intersystems.com/intersystems/iris-community:2023.1.0.235.1
    hostname: iris

    ports:
    # superserver default port 
    - "1972:1972"
    # webserver/management portal port
    - "52873:52773"

    #command:
    #    --key /ISC/license/iris.key

    volumes:
    - ./:/ISC

    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/ISC/cpf/merge.cpf

    mem_limit: 1G

  dotnet-dev:
    build:
      context: dotnet60
      dockerfile: Dockerfile
    command: bash
    restart: always
    tty: true
    environment:
    - TZ=JST-9
    volumes:
    - ./:/source
      
  dotnet-run:
    build:
      context: dotnet60-runtime
      dockerfile: Dockerfile
    command: bash
    restart: always
    tty: true
    environment:
    - TZ=JST-9
    volumes:
    - ./:/source

    mem_limit: 1G
